-- 2026-09-21 Real teachings from the Overcomers Global Network YouTube channel.
--
-- Source: https://www.youtube.com/@overcomersglobalnetwork (UCkhxsNcdEF0lXMIEqJooiNg),
-- read with yt-dlp on 2026-09-21. Every video id, length and date is YouTube's own.
-- Titles are the channel's titles, cleaned only for spelling and ALL-CAPS.
-- Generated by gen_teachings.py; re-running is safe (upsert on slug).
--
-- Left out on purpose (not teachings, or cannot play inside the app):
--   A93cSVIP2H4  US THREATEN NIGERIA GOVERNMENT WITH MILITARY ACTION IF THEY REFUSE TO   -> news clip (Nigeria military threats)
--   YoHmwssagH4  Hear what Donald Trump said about  Charlie Kirk😞😞😞  -> news clip (Trump / Charlie Kirk)
--   rhDf-elmEJo  The shocking word Donald Trump said about Jesus🥹🥹  -> news clip (Trump)
--   SAwx0PquSF0  KIRK SHOOTER FOUND  -> news clip (Kirk shooter)
--   O6ZLQ8SV7sc  Was Charlie Kirk’s Assassin on the Roof? Video Shows Suspicious Moveme  -> news clip (Charlie Kirk)
--   KthSMYBvn-4  Comment Your Name and Prayer Request 🙏  -> channel promo (Comment Your Name and Prayer Request)
--   _EC788M2Ldo  Intro for Youtube  -> channel promo (Intro for Youtube)
--   0FB5fv22nTA  Preacher Prophesies On FB Live! 🤯  -> channel promo (Preacher Prophesies On FB Live)
--   hip4zliqoDo  SHARE YOUR PRAYER 🙏  -> channel promo (SHARE YOUR PRAYER)
--   vwfdpm4l5sY  Prayer time with the Holy Spirit  -> embedding disabled on YouTube
--   jP4TB1P5uCg  Overcomers Online Sunday Service  -> embedding disabled on YouTube
--   DP6v6odSsmI  Overcomers Online Sunday Service  -> embedding disabled on YouTube
--   w7ugWoomS0c  Overcomers Online Sunday Service  Kingdom of Series  -> embedding disabled on YouTube
--   8I6uaSpRVL8  O Lord Perseve my Soul  -> 32-second stream stub, no teaching in it
--   and all 94 YouTube Shorts.

-- 1. Seeded demo rows members could see. Archived, not deleted.
update public.sermons set status = 'archived', is_featured = false, updated_at = now()
 where slug = 'authority-under-assignment' and video_url = 'https://example.com/live';
update public.sermon_series set status = 'archived', updated_at = now()
 where slug in ('kingdom-authority', 'power-of-prayer')
   and created_at = '2026-06-14 04:40:12.44689+00';
update public.media_items set status = 'archived', is_featured = false, updated_at = now()
 where title = 'App Review PDF Smoke Test';
-- The owner's own post keeps its place; only the speaker's capitals are fixed.
update public.media_items set speaker = 'Prophet Joshua Matthews', updated_at = now()
 where title = 'Gospel of Salvation' and speaker = 'Prophet joshua matthews';

-- 2. Series.
insert into public.sermon_series (title, slug, description, speaker, cover_image_url, status, sort_order)
values
  ('The Gospel of Salvation', 'the-gospel-of-salvation', 'Why man needs saving, and how God saves. A teaching series that goes with the free book.', 'Prophet Joshua Matthews', 'https://i.ytimg.com/vi/G5h7XID3Re8/hqdefault.jpg', 'published', 10),
  ('Possessing the Gates', 'possessing-the-gates', 'Possessing the gates of your soul and body: the heart, the eyes and the mouth.', 'Prophet Joshua Matthews', 'https://i.ytimg.com/vi/p07gaN_KWyM/hqdefault.jpg', 'published', 20),
  ('Divine Intimacy', 'divine-intimacy', 'God is calling you back into the secret place.', null, 'https://i.ytimg.com/vi/uT6ihRZOkvI/hqdefault.jpg', 'published', 30),
  ('Lord, Teach Me to Yield', 'lord-teach-me-to-yield', 'Learning to yield to the Holy Spirit.', null, 'https://i.ytimg.com/vi/VP6Mvd-4jkQ/hqdefault.jpg', 'published', 40),
  ('The Kingdom of God', 'the-kingdom-of-god', 'Returning to Kingdom dominion and living with a heavenly mind.', null, 'https://i.ytimg.com/vi/oQlb2VqnKG8/hqdefault.jpg', 'published', 50),
  ('Prophetic Prayer', 'prophetic-prayer', 'Prophetic prayer and intercession to pray along with.', null, 'https://i.ytimg.com/vi/_exo7en6_p0/hqdefault.jpg', 'published', 60),
  ('Sunday Restoration Service', 'sunday-restoration-service', 'Full Sunday services from Overcomers Global Network.', null, 'https://i.ytimg.com/vi/6UmenbYMXoE/hqdefault.jpg', 'published', 70),
  ('Bible Study & Prayer', 'bible-study-and-prayer', 'Midweek Bible study and prayer.', null, 'https://i.ytimg.com/vi/TKa59kcUW1M/hqdefault.jpg', 'published', 80),
  ('Bible Study — South Africa', 'bible-study-south-africa', 'Foundational teaching for believers, taught with the South Africa family.', null, 'https://i.ytimg.com/vi/GWoq9wLO058/hqdefault.jpg', 'published', 90),
  ('Discipleship & Mentorship', 'discipleship-and-mentorship', 'Disciples training and divine mentorship classes.', null, 'https://i.ytimg.com/vi/WQ8gb94MXLQ/hqdefault.jpg', 'published', 100),
  ('21 Days of Spiritual Recharge', 'spiritual-recharge', 'Live sessions from the 21 days of spiritual recharge.', null, 'https://i.ytimg.com/vi/Ymfn1gAlQus/hqdefault.jpg', 'published', 110),
  ('Personal Wellness & Financial Class', 'personal-wellness-class', 'OGN Global personal wellness and financial classes.', null, 'https://i.ytimg.com/vi/9-BTuwYQZSQ/hqdefault.jpg', 'published', 120),
  ('Testimonies & Ministry Moments', 'testimonies', 'What God has done in the lives of people at Overcomers Global Network.', null, 'https://i.ytimg.com/vi/ZSs1ESCM7Hs/hqdefault.jpg', 'published', 130)
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  speaker = excluded.speaker,
  cover_image_url = excluded.cover_image_url,
  status = excluded.status,
  sort_order = excluded.sort_order,
  updated_at = now();

-- 3. Teachings.
insert into public.sermons (series_id, title, slug, speaker, scripture_reference, video_url, thumbnail_url, duration_seconds, status, is_featured, published_at)
select s.id, v.title, v.slug, v.speaker, v.scripture, v.video_url, v.thumbnail_url, v.duration_seconds::int, 'published'::public.message_status, false, v.published_at::timestamptz
from (values
  ('the-gospel-of-salvation', 'The Gospel of Salvation, Part 1: Why Man Needs Saving', 'yt-the-gospel-of-salvation-part-1-why-man-needs-saving-g5h7xi', 'Prophet Joshua Matthews', null, 'https://www.youtube.com/watch?v=G5h7XID3Re8', 'https://i.ytimg.com/vi/G5h7XID3Re8/hqdefault.jpg', 1139, '2026-09-17 12:00:00+00'),
  ('possessing-the-gates', 'The Strong Man and the Gate of the Mouth', 'yt-the-strong-man-and-the-gate-of-the-mouth-wwvexx', 'Prophet Joshua Matthews', null, 'https://www.youtube.com/watch?v=WwveXx6D93s', 'https://i.ytimg.com/vi/WwveXx6D93s/hqdefault.jpg', 2356, '2026-08-31 12:00:00+00'),
  ('prophetic-prayer', 'Prophetic Prayers with Prophet Joshua', 'yt-prophetic-prayers-with-prophet-joshua-htiyyf', 'Prophet Joshua Matthews', null, 'https://www.youtube.com/watch?v=hTIyyfr6lKk', 'https://i.ytimg.com/vi/hTIyyfr6lKk/hqdefault.jpg', 2817, '2026-08-28 12:00:00+00'),
  ('possessing-the-gates', 'Eye Gates — Possessing the Gates, Part 2', 'yt-eye-gates-possessing-the-gates-part-2-jesbbg', 'Prophet Joshua Matthews', null, 'https://www.youtube.com/watch?v=jeSbBG9xCi0', 'https://i.ytimg.com/vi/jeSbBG9xCi0/hqdefault.jpg', 3344, '2026-08-26 12:00:00+00'),
  ('the-kingdom-of-god', 'Developing the Heavenly Mind for Earthly Success', 'yt-developing-the-heavenly-mind-for-earthly-success-hepadl', 'Prophet Joshua Matthews', null, 'https://www.youtube.com/watch?v=hepADlRdTYI', 'https://i.ytimg.com/vi/hepADlRdTYI/hqdefault.jpg', 2262, '2026-08-21 12:00:00+00'),
  ('possessing-the-gates', 'The Gate of the Heart — Possessing the Gates, Part 1', 'yt-the-gate-of-the-heart-possessing-the-gates-part-1-p07gan', 'Prophet Joshua Matthews', null, 'https://www.youtube.com/watch?v=p07gaN_KWyM', 'https://i.ytimg.com/vi/p07gaN_KWyM/hqdefault.jpg', 2581, '2026-08-19 12:00:00+00'),
  ('prophetic-prayer', 'The Wind of God Prayer: 15 Minutes of Heavy Prophetic Intercession', 'yt-the-wind-of-god-prayer-15-minutes-of-heavy-prophetic-intercession-5sbeew', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=5sBEEWFYhR8', 'https://i.ytimg.com/vi/5sBEEWFYhR8/hqdefault.jpg', 901, '2026-08-03 12:00:00+00'),
  ('personal-wellness-class', 'OGN Global Personal Wellness & Financial Class — April 21, 2026', 'yt-ogn-global-personal-wellness-and-financial-class-april-21-2026-prymag', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=PRYMAgSb-4Q', 'https://i.ytimg.com/vi/PRYMAgSb-4Q/hqdefault.jpg', 1621, '2026-04-21 12:00:00+00'),
  ('divine-intimacy', 'The Secret Place: Where Heaven Touches Earth — Divine Intimacy, Part 3', 'yt-the-secret-place-where-heaven-touches-earth-divine-intimacy-part-3-kujlnv', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=KuJlNVmC0WU', 'https://i.ytimg.com/vi/KuJlNVmC0WU/hqdefault.jpg', 201, '2026-04-08 12:00:00+00'),
  ('personal-wellness-class', 'OGN Global Personal Wellness & Financial Class — April 7, 2026', 'yt-ogn-global-personal-wellness-and-financial-class-april-7-2026-9btuwy', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=9-BTuwYQZSQ', 'https://i.ytimg.com/vi/9-BTuwYQZSQ/hqdefault.jpg', 2472, '2026-04-07 12:00:00+00'),
  ('divine-intimacy', 'The Language of the Spirit: Learning to Hear God''s Voice — Divine Intimacy, Part 2', 'yt-the-language-of-the-spirit-learning-to-hear-gods-voice-divine-intimacy-arutgk', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=arUtGKHMUac', 'https://i.ytimg.com/vi/arUtGKHMUac/hqdefault.jpg', 195, '2026-04-02 12:00:00+00'),
  ('divine-intimacy', 'The Invitation: God Is Calling You Back — Divine Intimacy, Part 1', 'yt-the-invitation-god-is-calling-you-back-divine-intimacy-part-1-ut6ihr', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=uT6ihRZOkvI', 'https://i.ytimg.com/vi/uT6ihRZOkvI/hqdefault.jpg', 183, '2026-04-01 12:00:00+00'),
  ('prophetic-prayer', 'Spirit of Prophecy', 'yt-spirit-of-prophecy-d6n5jq', 'Prophet Joshua Matthews', null, 'https://www.youtube.com/watch?v=d6n5JQO7rQg', 'https://i.ytimg.com/vi/d6n5JQO7rQg/hqdefault.jpg', 81, '2025-11-20 12:00:00+00'),
  ('the-kingdom-of-god', 'Returning to Kingdom Dominion', 'yt-returning-to-kingdom-dominion-eziith', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=ezIITH6iUac', 'https://i.ytimg.com/vi/ezIITH6iUac/hqdefault.jpg', 4317, '2025-10-12 12:00:00+00'),
  ('the-kingdom-of-god', 'Kingdom of God', 'yt-kingdom-of-god-oqlb2v', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=oQlb2VqnKG8', 'https://i.ytimg.com/vi/oQlb2VqnKG8/hqdefault.jpg', 3604, '2025-10-05 12:00:00+00'),
  ('lord-teach-me-to-yield', 'Lord, Teach Me to Yield — Part 3', 'yt-lord-teach-me-to-yield-part-3-5ovg4q', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=5OvG4Qgy_Is', 'https://i.ytimg.com/vi/5OvG4Qgy_Is/hqdefault.jpg', 3365, '2025-10-03 12:00:00+00'),
  ('lord-teach-me-to-yield', 'Lord, Teach Me How to Yield — Part 2', 'yt-lord-teach-me-how-to-yield-part-2-ruucxn', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=rUuCXnJYo8w', 'https://i.ytimg.com/vi/rUuCXnJYo8w/hqdefault.jpg', 4141, '2025-09-26 12:00:00+00'),
  ('lord-teach-me-to-yield', 'Lord, Teach Me to Yield — Part 1', 'yt-lord-teach-me-to-yield-part-1-vp6mvd', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=VP6Mvd-4jkQ', 'https://i.ytimg.com/vi/VP6Mvd-4jkQ/hqdefault.jpg', 3318, '2025-09-09 12:00:00+00'),
  ('testimonies', 'Pastor Daniel Saw Angels', 'yt-pastor-daniel-saw-angels-t50big', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=T50BIGH4Nsg', 'https://i.ytimg.com/vi/T50BIGH4Nsg/hqdefault.jpg', 872, '2025-09-09 12:00:00+00'),
  ('sunday-restoration-service', 'Sunday Restoration Service — August 10, 2025', 'yt-sunday-restoration-service-august-10-2025-9a3vgf', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=9A3VgfpKcQ4', 'https://i.ytimg.com/vi/9A3VgfpKcQ4/hqdefault.jpg', 11408, '2025-08-10 12:00:00+00'),
  ('sunday-restoration-service', 'Sunday Restoration Service — July 13, 2025', 'yt-sunday-restoration-service-july-13-2025-aekkvd', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=aeKkVD5nR3I', 'https://i.ytimg.com/vi/aeKkVD5nR3I/hqdefault.jpg', 6459, '2025-07-13 12:00:00+00'),
  ('sunday-restoration-service', 'Sunday Restoration Service — June 29, 2025', 'yt-sunday-restoration-service-june-29-2025-dyszsp', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=DYSZsPJKpIs', 'https://i.ytimg.com/vi/DYSZsPJKpIs/hqdefault.jpg', 9627, '2025-06-29 12:00:00+00'),
  ('sunday-restoration-service', 'Sunday Restoration Service — June 22, 2025 (Full Service)', 'yt-sunday-restoration-service-june-22-2025-full-service-b8qy8w', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=B8qY8wTwKYM', 'https://i.ytimg.com/vi/B8qY8wTwKYM/hqdefault.jpg', 7096, '2025-06-22 12:00:00+00'),
  ('sunday-restoration-service', 'Sunday Restoration Service — June 22, 2025 (Short)', 'yt-sunday-restoration-service-june-22-2025-short-63dokl', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=_63DoKLZsRU', 'https://i.ytimg.com/vi/_63DoKLZsRU/hqdefault.jpg', 983, '2025-06-22 12:00:00+00'),
  ('discipleship-and-mentorship', 'Disciples Training', 'yt-disciples-training-sc4zjn', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=SC4ZjNI8h8Q', 'https://i.ytimg.com/vi/SC4ZjNI8h8Q/hqdefault.jpg', 1886, '2025-06-16 12:00:00+00'),
  ('sunday-restoration-service', 'Sunday Restoration Service — June 15, 2025', 'yt-sunday-restoration-service-june-15-2025-u3zk4l', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=u3ZK4lHHtDs', 'https://i.ytimg.com/vi/u3ZK4lHHtDs/hqdefault.jpg', 9548, '2025-06-15 12:00:00+00'),
  ('sunday-restoration-service', 'Sunday Restoration Service — June 8, 2025', 'yt-sunday-restoration-service-june-8-2025-ugwwey', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=UGWWey4dxbo', 'https://i.ytimg.com/vi/UGWWey4dxbo/hqdefault.jpg', 10428, '2025-06-08 12:00:00+00'),
  ('bible-study-and-prayer', 'Bible Study & Prayer — June 4, 2025', 'yt-bible-study-and-prayer-june-4-2025-cpie6s', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=cPIe6-SJL0o', 'https://i.ytimg.com/vi/cPIe6-SJL0o/hqdefault.jpg', 2595, '2025-06-04 12:00:00+00'),
  ('bible-study-and-prayer', 'O Lord, Preserve My Soul', 'yt-o-lord-preserve-my-soul-qp3byy', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=qp3Byyk6UJc', 'https://i.ytimg.com/vi/qp3Byyk6UJc/hqdefault.jpg', 9083, '2025-06-01 12:00:00+00'),
  ('spiritual-recharge', 'Day 21 of 21: Spiritual Recharge', 'yt-day-21-of-21-spiritual-recharge-5vuhvx', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=5VUHVxyWMbE', 'https://i.ytimg.com/vi/5VUHVxyWMbE/hqdefault.jpg', 10988, '2025-05-28 12:00:00+00'),
  ('spiritual-recharge', 'Day 20 of 21: Spiritual Recharge', 'yt-day-20-of-21-spiritual-recharge-ymfn1g', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=Ymfn1gAlQus', 'https://i.ytimg.com/vi/Ymfn1gAlQus/hqdefault.jpg', 7815, '2025-05-27 12:00:00+00'),
  ('bible-study-and-prayer', 'Outpouring of Grace', 'yt-outpouring-of-grace-awq8tx', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=awq8TXZZsqQ', 'https://i.ytimg.com/vi/awq8TXZZsqQ/hqdefault.jpg', 6479, '2025-01-22 12:00:00+00'),
  ('bible-study-and-prayer', 'Outpouring of Grace — Bible Study', 'yt-outpouring-of-grace-bible-study-pmq8g6', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=PMq8g6wt1E4', 'https://i.ytimg.com/vi/PMq8g6wt1E4/hqdefault.jpg', 1785, '2025-01-22 12:00:00+00'),
  ('bible-study-and-prayer', 'Bible Study — January 8, 2025', 'yt-bible-study-january-8-2025-tka59k', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=TKa59kcUW1M', 'https://i.ytimg.com/vi/TKa59kcUW1M/hqdefault.jpg', 10062, '2025-01-08 12:00:00+00'),
  ('testimonies', 'Experiencing Heavenly Chariots on a Sunday Morning', 'yt-experiencing-heavenly-chariots-on-a-sunday-morning-odxkm3', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=oDxkm3tkYi8', 'https://i.ytimg.com/vi/oDxkm3tkYi8/hqdefault.jpg', 169, '2025-01-06 12:00:00+00'),
  ('prophetic-prayer', 'The Holy Spirit Is Our Deliverer', 'yt-the-holy-spirit-is-our-deliverer-qc4cqz', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=qC4cqz0Es9M', 'https://i.ytimg.com/vi/qC4cqz0Es9M/hqdefault.jpg', 95, '2024-12-13 12:00:00+00'),
  ('testimonies', '11 Years of Struggle Ended in One Encounter with Jesus', 'yt-11-years-of-struggle-ended-in-one-encounter-with-jesus-3jbzw3', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=3JBzw3_CEao', 'https://i.ytimg.com/vi/3JBzw3_CEao/hqdefault.jpg', 431, '2024-12-13 12:00:00+00'),
  ('bible-study-south-africa', 'Bible Study: The Power of Forgiveness', 'yt-bible-study-the-power-of-forgiveness-dtnqse', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=DtnQsesW0o4', 'https://i.ytimg.com/vi/DtnQsesW0o4/hqdefault.jpg', 11215, '2024-12-04 12:00:00+00'),
  ('prophetic-prayer', 'Prayers to Shift Seasons', 'yt-prayers-to-shift-seasons-2urnmh', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=2uRnmHPjrho', 'https://i.ytimg.com/vi/2uRnmHPjrho/hqdefault.jpg', 1164, '2024-11-25 12:00:00+00'),
  ('bible-study-south-africa', 'Bible Study — South Africa — November 20, 2024', 'yt-bible-study-south-africa-november-20-2024-zlzfok', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=z_LZfOKw6IM', 'https://i.ytimg.com/vi/z_LZfOKw6IM/hqdefault.jpg', 10677, '2024-11-20 12:00:00+00'),
  ('testimonies', 'A Life-Changing Experience with Narkita at Overcomers Global Network', 'yt-a-life-changing-experience-with-narkita-at-overcomers-global-network-5czod9', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=5CzO_d9GZBo', 'https://i.ytimg.com/vi/5CzO_d9GZBo/hqdefault.jpg', 153, '2024-11-20 12:00:00+00'),
  ('testimonies', 'Powerful Testimony with Prophetess Bobbie Rush', 'yt-powerful-testimony-with-prophetess-bobbie-rush-6vdazn', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=6v_DAZnCe1c', 'https://i.ytimg.com/vi/6v_DAZnCe1c/hqdefault.jpg', 180, '2024-11-20 12:00:00+00'),
  ('discipleship-and-mentorship', 'Divine Mentorship Class — November 14, 2024', 'yt-divine-mentorship-class-november-14-2024-wfaevl', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=WFAevLoKjiM', 'https://i.ytimg.com/vi/WFAevLoKjiM/hqdefault.jpg', 5695, '2024-11-14 12:00:00+00'),
  ('bible-study-south-africa', 'OGN Bible Study: Foundational Principles', 'yt-ogn-bible-study-foundational-principles-he7h26', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=he7H26EpgxQ', 'https://i.ytimg.com/vi/he7H26EpgxQ/hqdefault.jpg', 8336, '2024-11-13 12:00:00+00'),
  ('discipleship-and-mentorship', 'Divine Mentorship Class — November 7, 2024', 'yt-divine-mentorship-class-november-7-2024-wktbap', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=wktBApoTn0c', 'https://i.ytimg.com/vi/wktBApoTn0c/hqdefault.jpg', 3742, '2024-11-07 12:00:00+00'),
  ('bible-study-south-africa', 'OGN Bible Study: Laying the Foundations of the Believer', 'yt-ogn-bible-study-laying-the-foundations-of-the-believer-q7psr8', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=Q7PSr85Dago', 'https://i.ytimg.com/vi/Q7PSr85Dago/hqdefault.jpg', 6895, '2024-11-06 12:00:00+00'),
  ('bible-study-south-africa', 'Ultimate Journey with Jesus Christ: Foundational Principles Every Believer Needs', 'yt-ultimate-journey-with-jesus-christ-foundational-principles-every-belie-htijev', 'Overcomers Global Network', 'Hebrews 6:1-3', 'https://www.youtube.com/watch?v=HtIjeV79dxI', 'https://i.ytimg.com/vi/HtIjeV79dxI/hqdefault.jpg', 9675, '2024-10-30 12:00:00+00'),
  ('bible-study-south-africa', 'Bible Study: The Foundational Teaching of Baptism', 'yt-bible-study-the-foundational-teaching-of-baptism-l5ysg6', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=L5Ysg6Y0Qg0', 'https://i.ytimg.com/vi/L5Ysg6Y0Qg0/hqdefault.jpg', 2775, '2024-10-16 12:00:00+00'),
  ('bible-study-south-africa', 'OGN Bible Study: Foundational Teachings', 'yt-ogn-bible-study-foundational-teachings-gwoq9w', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=GWoq9wLO058', 'https://i.ytimg.com/vi/GWoq9wLO058/hqdefault.jpg', 4141, '2024-10-09 12:00:00+00'),
  ('testimonies', 'Overcomers Global Network Community Event', 'yt-overcomers-global-network-community-event-zss1es', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=ZSs1ESCM7Hs', 'https://i.ytimg.com/vi/ZSs1ESCM7Hs/hqdefault.jpg', 205, '2024-09-22 12:00:00+00'),
  ('prophetic-prayer', 'Prayer for You: Open Doors', 'yt-prayer-for-you-open-doors-lomp6f', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=lomP6fxqqW0', 'https://i.ytimg.com/vi/lomP6fxqqW0/hqdefault.jpg', 318, '2024-09-21 12:00:00+00'),
  ('sunday-restoration-service', 'Overcomers Online Sunday Service: Glorious God', 'yt-overcomers-online-sunday-service-glorious-god-6umenb', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=6UmenbYMXoE', 'https://i.ytimg.com/vi/6UmenbYMXoE/hqdefault.jpg', 721, '2024-09-08 12:00:00+00'),
  ('prophetic-prayer', 'Powerful Prophetic Prayers 2024', 'yt-powerful-prophetic-prayers-2024-exo7en', 'Overcomers Global Network', null, 'https://www.youtube.com/watch?v=_exo7en6_p0', 'https://i.ytimg.com/vi/_exo7en6_p0/hqdefault.jpg', 1318, '2024-08-02 12:00:00+00'),
  ('discipleship-and-mentorship', 'The Heart of the Disciple', 'yt-the-heart-of-the-disciple-dfqhdb', 'Whitney Alexander', null, 'https://www.youtube.com/watch?v=DfQHDbqU6aU', 'https://i.ytimg.com/vi/DfQHDbqU6aU/hqdefault.jpg', 1526, '2024-06-08 12:00:00+00'),
  ('discipleship-and-mentorship', 'How to Identify Your Spiritual Father', 'yt-how-to-identify-your-spiritual-father-wq8gb9', 'Whitney Alexander', null, 'https://www.youtube.com/watch?v=WQ8gb94MXLQ', 'https://i.ytimg.com/vi/WQ8gb94MXLQ/hqdefault.jpg', 1636, '2024-06-02 12:00:00+00')
) as v(series_slug, title, slug, speaker, scripture, video_url, thumbnail_url, duration_seconds, published_at)
join public.sermon_series s on s.slug = v.series_slug
on conflict (slug) do update set
  series_id = excluded.series_id,
  title = excluded.title,
  speaker = excluded.speaker,
  scripture_reference = excluded.scripture_reference,
  video_url = excluded.video_url,
  thumbnail_url = excluded.thumbnail_url,
  duration_seconds = excluded.duration_seconds,
  status = excluded.status,
  published_at = excluded.published_at,
  updated_at = now();
